In [ ]:
import numpy as np
outfile = r'.\test.npy'
np.random.seed(20200619)
x = np.random.uniform(0, 1, [3, 5])
np.save(outfile, x)
y = np.load(outfile)
print(y)

In [3]:
outfile = r'.\test.npz'
x = np.linspace(0, np.pi, 5)
y = np.sin(x)
z = np.cos(x)
np.savez(outfile, x, y, z_d=z)
data = np.load(outfile)
np.set_printoptions(suppress=True)
print(data.files)
# ['z_d', 'arr_0', 'arr_1']
print(data['arr_0'])
# [0.         0.78539816 1.57079633 2.35619449 3.14159265]
print(data['arr_1'])
# [0.         0.70710678 1.         0.70710678 0.        ]
print(data['z_d'])
# [ 1.          0.70710678  0.         ‐0.70710678 ‐1.]

['z_d', 'arr_0', 'arr_1']
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.         0.70710678 1.         0.70710678 0.        ]
[ 1.          0.70710678  0.         -0.70710678 -1.        ]


In [7]:
outfile = r'.\test.txt'
x = np.arange(0, 10).reshape(2,‐1) 
np.savetxt(outfile, x)
y = np.loadtxt(outfile)
print(y)
# [[0. 1. 2. 3. 4.]
# [5.6.7.8.9.]]

SyntaxError: invalid character in identifier (<ipython-input-7-bb09bc277835>, line 2)

In [ ]:
import numpy as np
outfile = r'.\test.csv'
x = np.arange(0, 10, 0.5).reshape(4, ‐1) np.savetxt(outfile, x, fmt='%.3f', delimiter=',') y = np.loadtxt(outfile, delimiter=',')
print(y)
#[[0. 0.51. 1.52.]
# [2.5 3. 3.5 4. 4.5]
# [5. 5.56. 6.57.]
# [7.5 8. 8.5 9. 9.5]]

In [9]:
outfile = r'.\data.csv'
x = np.loadtxt(outfile, delimiter=',', skiprows=1) print(x)
#[[ 1. 123. 1.4 23.]
#[2.110. 0.518.]
# [ 3. 164. 2.1 19.]]
x = np.loadtxt(outfile, delimiter=',', skiprows=1, usecols=(1, 2))
print(x)
# [[123.    1.4]
#  [110.    0.5]
# [164. 2.1]]
val1, val2 = np.loadtxt(outfile, delimiter=',', skiprows=1, usecols=(1, 2), unpack=True)
print(val1)  # [123. 110. 164.]
print(val2)  # [1.4 0.5 2.1]

SyntaxError: invalid syntax (<ipython-input-9-c87a5cb1b493>, line 2)

In [10]:
import numpy as np
outfile = r'.\data.csv'
x = np.genfromtxt(outfile, delimiter=',', names=True)
print(x)
# [(1., 123., 1.4, 23.) (2., 110., 0.5, 18.) (3., 164., 2.1, 19.)]
print(type(x))
# <class 'numpy.ndarray'>
print(x.dtype)
# [('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')]
print(x['id'])  # [1. 2. 3.]
print(x['value1'])  # [123. 110. 164.]
print(x['value2'])  # [1.4 0.5 2.1]
print(x['value3'])  # [23. 18. 19.]

OSError: .\data.csv not found.

In [11]:
import numpy as np
outfile = r'.\data.csv'
x = np.genfromtxt(outfile, delimiter=',', names=True)
print(x)
# [(1., 123., 1.4, 23.) (2., 110., 0.5, 18.) (3., 164., 2.1, 19.)]
print(type(x))
# <class 'numpy.ndarray'>
print(x.dtype)
# [('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')]
print(x['id'])  # [1. 2. 3.]
print(x['value1'])  # [123. 110. 164.]
print(x['value2'])  # [1.4 0.5 2.1]
print(x['value3'])  # [23. 18. 19.]

OSError: .\data.csv not found.

In [12]:
np.set_printoptions(precision=4)
x = np.array([1.123456789])    

In [13]:
np.set_printoptions(threshold=20)
x = np.arange(50)
print(x) #[0 1 2...474849]
np.set_printoptions(threshold=np.iinfo(np.int).max)
print(x)
#[0 1 2 3 4 5 6 7 8 91011121314151617181920212223 # 242526272829303132333435363738394041424344454647 # 48 49]
eps = np.finfo(float).eps
x = np.arange(4.)
x = x ** 2 ‐ (x + eps) ** 2
print(x)
# [‐4.9304e‐32 ‐4.4409e‐16  0.0000e+00  0.0000e+00]
np.set_printoptions(suppress=True)
print(x)  # [‐0. ‐0.  0.  0.]
x = np.linspace(0, 10, 10)
print(x)
# [ 0. 1.1111 2.2222 3.3333 4.4444 5.5556 6.6667 7.7778 8.8889 #10. ]
np.set_printoptions(precision=2, suppress=True, threshold=5)
print(x) # [ 0. 1.11 2.22 ... 7.78 8.89 10. ]

SyntaxError: invalid character in identifier (<ipython-input-13-d4973aec071d>, line 9)